# Generated by Django 5.2.6 on 2025-10-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_request_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
