# Generated by Django 5.2.6 on 2025-12-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_level',
            field=models.CharField(max_length=5),
        ),
    ]
