# Generated by Django 5.2.6 on 2025-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_role_alter_profile_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
    ]
