# Generated by Django 5.2.6 on 2025-12-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, help_text='Permanent address', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about yourself', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, choices=[('BS Architecture', 'BS Architecture'), ('BS Chemical Engineering', 'BS Chemical Engineering'), ('BS Civil Engineering', 'BS Civil Engineering'), ('BS Computer Engineering', 'BS Computer Engineering'), ('BS Computer Science', 'BS Computer Science'), ('BS Electrical Engineering', 'BS Electrical Engineering'), ('BS Electronics Engineering', 'BS Electronics Engineering'), ('BS Industrial Engineering', 'BS Industrial Engineering'), ('BS Information Technology', 'BS Information Technology'), ('BS Mechanical Engineering with Computational Science', 'BS Mechanical Engineering with Computational Science'), ('BS Mechanical Engineering with Mechatronics', 'BS Mechanical Engineering with Mechatronics'), ('BS Mining Engineering', 'BS Mining Engineering')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin')], default='STUDENT', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
    ]
