# Generated by Django 5.2.6 on 2025-11-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_attachment'),
    ]

    operations = [
    ]
