# Generated by Django 5.2.6 on 2025-11-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_category_tag_alter_request_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
