# Generated by Django 5.2.6 on 2025-12-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='request_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='category_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request_app.categorychoice'),
        ),
    ]
