# Generated by Django 5.2.6 on 2025-11-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0002_alter_request_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Course Material', 'Course Material'), ('Grades', 'Grades'), ('Assignments', 'Assignments'), ('Exam Schedule', 'Exam Schedule'), ('Finance', 'Finance'), ('Tuition Fee', 'Tuition Fee'), ('Scholarship', 'Scholarship'), ('Refund', 'Refund'), ('Technical', 'Technical'), ('Login Issue', 'Login Issue'), ('Software Installation', 'Software Installation'), ('Wi-Fi / Network Issue', 'Wi-Fi / Network Issue'), ('Administrative', 'Administrative'), ('ID Card', 'ID Card'), ('Room Allocation', 'Room Allocation'), ('Library Access', 'Library Access')], default='Academic', max_length=50),
        ),
    ]
