# Generated by Django 5.2.6 on 2025-11-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0003_alter_request_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
