# Generated by Django 5.2.6 on 2025-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notification_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
