# Generated by Django 5.2.6 on 2025-12-09 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('request_app', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='request_app.request'),
        ),
    ]
